### ISSUE TITLE
FR: [Frontend] - GraphQL API Cross-reference Search 

### ISSUE THREAD

**Issue by palmajano** [aemsites/vg-roadchoice-com#69]
### Context/Description

The search interface is exposed to the Front end by means of a GraphQL endpoint that performs the actual OpenSearch query and returns the results in an understandable format for the front end.
Thus, the front end needs to be updated to use the new GraphQL endpoint developed in #47 

### Acceptance Criteria

- Only Preview mode is used which uses the url: [https://search-api-qa-eds.aws.43636.vnonprod.com/search](https://search-api-qa-eds.aws.43636.vnonprod.com/search)
- The front end uses the GraphQL endpoint `rccrossreferencesearch` when searching by Cross-reference.
- The search results can be paginated (12 items per page as currently).
- The results are displayed.
- The old search solution is still available.
- End-to-end testing for  #47

### Out of scope
- Replace existing "Categories" menu that displays to left of the results with CTA "Looking for a specific category?"  - the decision was made to keep it as is for the best user experience. 
- Categories should not load automatically. User must select CTA to expand the available categories related to the search results.  - the decision was made to keep it as is for the best user experience. 

- Deployment to Production (do not publish changes)
- Category facets and search

**Comment by ZoeBeykirch** [comment]
Once this ticket is completed, we can deploy the cross reference search to production

**Comment by cincplug** [comment]
Hi @AsmitKMishra you can test this on https://69-opensearch--vg-roadchoice-com--aemsites.hlx.page/

As agreed, I won't be merging it to develop branch until some backend dependencies are resolved, because having it in develop branch would block the release of any other Road choice tickets. So the code review with other devs will be done only then, but for now we still need to test the functionality.

As agreed, the cross-reference and part number search obtain the results from GraphQL in sequences of 12, and Show more button loads new sequence. The exception is when user clicks on any category in left sidebar, which triggers the old search and limits the category list to just that category.

**Comment by cincplug** [comment]
Hi @AsmitKMishra please test this now that it's merged to develop, sorry that it couldn't be sooner.
https://develop--vg-roadchoice-com--aemsites.hlx.page/
Now we also obtain category filters in the left sidebar from OpenSearch too, so category search now uses the same logic

**Comment by AsmitKMishra** [comment]
Testing Completed. Search feature works as expected.
